# Generated by Django 3.0.3 on 2020-04-19 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('nome', models.CharField(blank=True, max_length=50)),
                ('sobrenome', models.CharField(blank=True, max_length=50)),
                ('rg', models.CharField(blank=True, max_length=12)),
                ('cpf', models.CharField(blank=True, max_length=14, primary_key=True, serialize=False)),
                ('telefone', models.CharField(blank=True, max_length=14)),
                ('token', models.CharField(blank=True, max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
