# Generated by Django 3.0.3 on 2020-04-21 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_team', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfileInfo',
        ),
    ]
