# Generated by Django 3.0.3 on 2020-04-21 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='altura',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='peso',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
