# Generated by Django 3.0.3 on 2020-04-22 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_auto_20200421_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4),
        ),
    ]
