# Generated by Django 3.0.3 on 2020-04-22 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_auto_20200421_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asthmacontrolquestionnaire',
            name='date',
            field=models.DateField(),
        ),
    ]
