# Generated by Django 3.0.3 on 2020-04-22 01:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('server', '0007_auto_20200421_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitbitFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('path', models.FileField(upload_to='fitbit/<django.db.models.query_utils.DeferredAttribute object at 0x000002194DE433C8>/<django.db.models.fields.CharField>/')),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique_for_date='date')),
            ],
        ),
    ]
