# Generated by Django 3.0.3 on 2020-04-23 02:20

from django.db import migrations, models
import server.models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_fitbitfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='imagem',
            field=models.FileField(blank=True, upload_to=server.models.userImage_path),
        ),
        migrations.AlterField(
            model_name='fitbitfile',
            name='path',
            field=models.FileField(upload_to=server.models.fitbit_path),
        ),
    ]
