# Generated by Django 3.0.3 on 2020-05-08 01:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_goal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='daysToEnd',
        ),
        migrations.AddField(
            model_name='goal',
            name='endDate',
            field=models.DateField(default=datetime.date(2020, 5, 7)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goal',
            name='quantity',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
