# Generated by Django 3.0.3 on 2020-04-16 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='imcModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.CharField(max_length=5)),
                ('altura', models.CharField(max_length=5)),
            ],
        ),
    ]
